set -g status-style "bg={{background}},fg={{muted}}"
set -g status-left "#[fg={{accent_text}},bg={{accent}},bold] 󰆍 #S #[default] "
set -g status-right "#[fg={{muted}}]#(whoami)@#H  #[fg={{accent}}]%a %H:%M "
setw -g window-status-format " #[fg={{muted}}]#I:#W "
setw -g window-status-current-format "#[fg={{accent_text}},bg={{accent_soft}},bold] #I:#W "
set -g pane-border-style "fg={{border}}"
set -g pane-active-border-style "fg={{accent}}"
set -g message-style "bg={{panel}},fg={{accent}}"
