foreground {{foreground}}
background {{background}}
selection_foreground {{accent_text}}
selection_background {{accent}}
cursor {{accent}}
cursor_text_color {{accent_text}}
active_border_color {{accent}}
inactive_border_color {{border}}
active_tab_foreground {{accent_text}}
active_tab_background {{accent}}
inactive_tab_foreground {{foreground}}
inactive_tab_background {{panel}}
background_opacity 0.90
dynamic_background_opacity yes
background_blur 18
