set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-kitty:RGB"
set -g mouse on
set -g history-limit 100000
set -g focus-events on
set -g escape-time 0
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind r source-file /etc/tmux.conf \; display-message "ArcOS tmux reloaded"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-position top
set -g status-interval 2
set -g status-style "bg=#171923,fg=#b5bfe2"
set -g status-left-length 32
set -g status-right-length 80
set -g status-left "#[fg=#171923,bg=#cba6f7,bold] 󰆍 #S #[default] "
set -g status-right "#[fg=#838ba7]#(whoami)@#H  #[fg=#cba6f7]%a %H:%M "
setw -g window-status-format " #[fg=#838ba7]#I:#W "
setw -g window-status-current-format "#[fg=#171923,bg=#8f7aa8,bold] #I:#W "
set -g pane-border-style "fg=#303446"
set -g pane-active-border-style "fg=#cba6f7"
set -g message-style "bg=#303446,fg=#f4b8e4"
source-file -q ~/.config/tmux/arcos-theme.conf
