[package]
name = "arc-shell"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arc-protocol = { path = "../arc-protocol" }
anyhow.workspace = true
bytemuck = { version = "1", features = ["derive"] }
glyphon = "0.8"
serde_json.workspace = true
pollster = "0.4"
raw-window-handle = "0.6"
smithay-client-toolkit = "0.19"
wayland-client = { version = "0.31", features = ["system"] }
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
wgpu = "24"
uuid.workspace = true
